"""empty message

Revision ID: 274704865593
Revises: 073946a9e623
Create Date: 2020-12-23 15:11:29.167730

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '274704865593'
down_revision = '073946a9e623'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_history_called_on'), 'history', ['called_on'], unique=False)
    op.create_index(op.f('ix_history_backup_called_on'), 'history_backup', ['called_on'], unique=False)
    op.create_index(op.f('ix_history_test_called_on'), 'history_test', ['called_on'], unique=False)
    op.alter_column('telefonica', 'phone',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('telefonica_backup', 'phone',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('telefonica_test', 'phone',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('telefonica_test', 'phone',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('telefonica_backup', 'phone',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('telefonica', 'phone',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.drop_index(op.f('ix_history_test_called_on'), table_name='history_test')
    op.drop_index(op.f('ix_history_backup_called_on'), table_name='history_backup')
    op.drop_index(op.f('ix_history_called_on'), table_name='history')
    # ### end Alembic commands ###
