"""empty message

Revision ID: 28cb0be1f0d5
Revises: c2200a959bc6
Create Date: 2020-12-25 03:26:32.153749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28cb0be1f0d5'
down_revision = 'c2200a959bc6'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_mode', sa.Boolean(), nullable=False, server_default="0"),
    sa.Column('unanswered_max_attemps', sa.Integer(), nullable=False, server_default="3"),
    sa.Column('answering_machine_max_attemps', sa.Integer(), nullable=False, server_default="2"),
    sa.Column('answering_machine_postponed_days', sa.Integer(), nullable=False, server_default="10"),
    sa.Column('postponed_button_days', sa.Integer(), nullable=False, server_default="3"),
    sa.Column('non_existent_postponed_days', sa.Integer(), nullable=False, server_default="180"),
    sa.Column('hidden_buttons', sa.String(length=40), nullable=False, server_default=""),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configurations_test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_mode', sa.Boolean(), nullable=False, server_default="0"),
    sa.Column('unanswered_max_attemps', sa.Integer(), nullable=False, server_default="3"),
    sa.Column('answering_machine_max_attemps', sa.Integer(), nullable=False, server_default="2"),
    sa.Column('answering_machine_postponed_days', sa.Integer(), nullable=False, server_default="10"),
    sa.Column('postponed_button_days', sa.Integer(), nullable=False, server_default="3"),
    sa.Column('non_existent_postponed_days', sa.Integer(), nullable=False, server_default="180"),
    sa.Column('hidden_buttons', sa.String(length=40), nullable=False, server_default=""),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("insert into configurations values ();")
    op.execute("insert into configurations_test values ();")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configurations_test')
    op.drop_table('configurations')
    # ### end Alembic commands ###
