"""empty message

Revision ID: 81fc291e5908
Revises: 
Create Date: 2020-12-22 20:29:36.708132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81fc291e5908'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_id', sa.Integer(), nullable=True),
    sa.Column('called_on', sa.Date(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('genuine', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('history_test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_id', sa.Integer(), nullable=True),
    sa.Column('called_on', sa.Date(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('genuine', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telefonica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('direccion', sa.String(length=40), nullable=True),
    sa.Column('telefono', sa.String(length=40), nullable=True),
    sa.Column('answered_on', sa.DateTime(), nullable=True),
    sa.Column('fulfilled_on', sa.Date(), nullable=True),
    sa.Column('comentarios', sa.String(length=100), nullable=True),
    sa.Column('no_call', sa.Boolean(), nullable=True),
    sa.Column('non_existent', sa.Boolean(), nullable=True),
    sa.Column('unanswered_count', sa.Integer(), nullable=True),
    sa.Column('unanswered_date', sa.DateTime(), nullable=True),
    sa.Column('postponed_days', sa.Integer(), nullable=True),
    sa.Column('commented_on', sa.Date(), nullable=True),
    sa.Column('answering_machine_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telefonica_test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('direccion', sa.String(length=40), nullable=True),
    sa.Column('telefono', sa.String(length=40), nullable=True),
    sa.Column('answered_on', sa.DateTime(), nullable=True),
    sa.Column('fulfilled_on', sa.Date(), nullable=True),
    sa.Column('comentarios', sa.String(length=100), nullable=True),
    sa.Column('no_call', sa.Boolean(), nullable=True),
    sa.Column('non_existent', sa.Boolean(), nullable=True),
    sa.Column('unanswered_count', sa.Integer(), nullable=True),
    sa.Column('unanswered_date', sa.DateTime(), nullable=True),
    sa.Column('postponed_days', sa.Integer(), nullable=True),
    sa.Column('commented_on', sa.Date(), nullable=True),
    sa.Column('answering_machine_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('telefonica_test')
    op.drop_table('telefonica')
    op.drop_table('history_test')
    op.drop_table('history')
    # ### end Alembic commands ###
