"""empty message

Revision ID: c2200a959bc6
Revises: 274704865593
Create Date: 2020-12-24 15:08:35.978414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2200a959bc6'
down_revision = '274704865593'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telefonica', sa.Column('no_weekends', sa.Boolean(), nullable=False))
    op.add_column('telefonica_test', sa.Column('no_weekends', sa.Boolean(), nullable=False))
    op.add_column('telefonica_backup', sa.Column('no_weekends', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telefonica', 'no_weekends')
    op.drop_column('telefonica_test', 'no_weekends')
    op.drop_column('telefonica_backup', 'no_weekends')
    # ### end Alembic commands ###
