"""empty message

Revision ID: d231efd2533a
Revises: 098851515a09
Create Date: 2020-12-30 16:13:40.498290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd231efd2533a'
down_revision = '098851515a09'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('watch_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_executed', sa.Date(), nullable=True),
    sa.Column('last_checked', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("insert into watch_task values (1, null, null);")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watch_task')
    # ### end Alembic commands ###
